project:
  type: website
  output-dir: .

website:
  title: "Conor-English.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects/index.qmd
        text: Projects
      - href: projects/resume.qmd
        text: Resume
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
