project:
  type: website
  output-dir: docs

website:
  title: "Conor-English.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects/index.qmd
        text: Projects
      - href: resume.qmd
        text: Resume
      - href: about.qmd
        text: About
      - href: reflection.qmd
        text: Reflection

format:
  html:
    theme: cosmo
    toc: true
    css: styles.css   
